const map=L.map('map').setView([52.15,5.35],8);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap contributors'}).addTo(map);
map.createPane('notamPane');map.getPane('notamPane').style.zIndex=350;
map.createPane('corridorPane');map.getPane('corridorPane').style.zIndex=420;
map.createPane('taskPane');map.getPane('taskPane').style.zIndex=460;
const $=id=>document.getElementById(id),STORE='soaring-notam-v12',STALE_MINUTES=60;$('date').value=new Date().toISOString().slice(0,10);
let points=[],markers=[],track=null,corridorLayer=null,notamLayers=[],notams=[],dataError=null,showRelevant=false,showAll=false;
const R=6371,rad=x=>x*Math.PI/180;
function hav(a,b){const dlat=rad(b.lat-a.lat),dlon=rad(b.lng-a.lng);const q=Math.sin(dlat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function segDistance(p,a,b){const lat0=rad(p.lat);const sx=x=>({x:rad(x.lng-p.lng)*Math.cos(lat0)*R,y:rad(x.lat-p.lat)*R});const A=sx(a),B=sx(b),vx=B.x-A.x,vy=B.y-A.y,wx=-A.x,wy=-A.y;const t=Math.max(0,Math.min(1,(wx*vx+wy*vy)/(vx*vx+vy*vy||1)));return Math.hypot(A.x+t*vx,A.y+t*vy)}
function legs(){if(points.length<2)return[];const arr=[];for(let i=0;i<points.length-1;i++)arr.push([points[i],points[i+1]]);if($('taskType').value==='triangle'&&points.length===3)arr.push([points[2],points[0]]);return arr}
function taskDistance(){return legs().reduce((s,[a,b])=>s+hav(a,b),0)}
function taskCoords(){if(points.length<2)return null;const c=points.map(p=>[p.lng,p.lat]);if($('taskType').value==='triangle'&&points.length===3)c.push([points[0].lng,points[0].lat]);return c}
function updateLegInfo(){const ls=legs();$('legInfo').innerHTML=ls.map(([a,b],i)=>`<span>Leg ${i+1}: <strong>${hav(a,b).toFixed(1)} km</strong></span>`).join('')}
function saveState(){localStorage.setItem(STORE,JSON.stringify({points:points.map(p=>[p.lat,p.lng]),date:$('date').value,corridor:$('corridor').value,alt:$('alt').value,taskType:$('taskType').value}))}
function corridorGeoJSON(){const coords=taskCoords();return coords&&window.turf?turf.buffer(turf.lineString(coords),+$('corridor').value,{units:'kilometers',steps:32}):null}
function rebuild(){if(track)map.removeLayer(track);if(corridorLayer)map.removeLayer(corridorLayer);track=null;corridorLayer=null;const ls=legs(),buffered=corridorGeoJSON();if(ls.length){if(buffered)corridorLayer=L.geoJSON(buffered,{pane:'corridorPane',style:{weight:1,opacity:.45,fillOpacity:.035}}).addTo(map);track=L.polyline(ls.map(x=>x.map(p=>[p.lat,p.lng])),{pane:'taskPane',weight:5,opacity:1}).addTo(map)}$('taskInfo').textContent=points.length?`${points.length} points · ${taskDistance().toFixed(0)} km task · ${$('corridor').value} km corridor`:'No task';updateLegInfo();filterNotams();saveState()}
function markerLabel(i){return i===0?'HOME':`TP${i}`}
function addPoint(latlng,doRebuild=true){if($('taskType').value==='triangle'&&points.length>=3)return;const i=points.length;points.push(latlng);const m=L.marker(latlng,{draggable:true}).addTo(map).bindTooltip(markerLabel(i),{permanent:true,direction:'top'});m.on('drag',()=>{points[i]=m.getLatLng();rebuild()});markers.push(m);if(doRebuild)rebuild()}
function clearTask(){points=[];markers.forEach(m=>map.removeLayer(m));markers=[];rebuild()}
map.on('click',e=>addPoint(e.latlng));$('start').onclick=clearTask;$('undo').onclick=()=>{if(!points.length)return;points.pop();map.removeLayer(markers.pop());rebuild()};$('demo').onclick=()=>{clearTask();[[52.191,5.146],[52.26,6.18],[52.78,6.49]].forEach(([lat,lng])=>addPoint(L.latLng(lat,lng),false));rebuild();if(track)map.fitBounds(track.getBounds().pad(.25))};
$('taskType').onchange=()=>{if($('taskType').value==='triangle'&&points.length>3){while(points.length>3){points.pop();map.removeLayer(markers.pop())}}rebuild()};['corridor','alt','date'].forEach(id=>$(id).onchange=rebuild);
function activeOn(n,date){return (!n.valid_from||n.valid_from.slice(0,10)<=date)&&(!n.valid_to||n.valid_to.slice(0,10)>=date)}
function featureForGeometry(geometry){return geometry?{type:'Feature',properties:{},geometry}:null}
function geometryParts(geometry){return geometry&&geometry.type==='GeometryCollection'?geometry.geometries.flatMap(geometryParts):geometry?[geometry]:[]}
function relevant(n){if(points.length<2||n.status==='CANCELLED'||!activeOn(n,$('date').value)||Number(n.lower_ft||0)>+$('alt').value)return false;const buffered=corridorGeoJSON();if(!buffered)return false;return geometryParts(n.geometry).some(geometry=>{if(geometry.type==='Point'){const [lon,lat]=geometry.coordinates,radius=Number(n.radius_km||0),d=Math.min(...legs().map(([a,b])=>segDistance(L.latLng(lat,lon),a,b)));return d<=+$('corridor').value+radius}try{return turf.booleanIntersects(buffered,featureForGeometry(geometry))}catch{return false}})}
function coordinatePairs(value,out=[]){if(Array.isArray(value)&&value.length>=2&&typeof value[0]==='number'&&typeof value[1]==='number')out.push(value);else if(Array.isArray(value))value.forEach(x=>coordinatePairs(x,out));return out}
function distanceToTask(n){const ls=legs();if(!ls.length)return Infinity;const line=turf.lineString(taskCoords()),radius=Number(n.radius_km||0);let best=Infinity,direct=false;geometryParts(n.geometry).forEach(geometry=>{if(geometry.type==='Point'){const [lon,lat]=geometry.coordinates,d=Math.max(0,Math.min(...ls.map(([a,b])=>segDistance(L.latLng(lat,lon),a,b)))-radius);best=Math.min(best,d);if(d===0)direct=true;return}try{if(turf.booleanIntersects(line,featureForGeometry(geometry)))direct=true}catch{}coordinatePairs(geometry.coordinates).forEach(([lon,lat])=>{best=Math.min(best,...ls.map(([a,b])=>segDistance(L.latLng(lat,lon),a,b)))})});return direct?0:best}
function relationToTask(distance){return distance<.05?'on route':`${distance<10?distance.toFixed(1):Math.round(distance)} km from task`}
function displayTime(value){return value?value.replace('T',' ').replace(/:00Z$/,'Z'):'—'}
function popupHtml(n){return `<b>${n.id}</b> · ${n.category||n.relevance.replace('_RELEVANCE','')}<div class="popupmeta"><b>${relationToTask(n.distance_to_task_km)}</b><br>${n.lower_ft||0}–${n.upper_ft||'—'} ft<br>${displayTime(n.valid_from)} → ${displayTime(n.valid_to)}<br>Q-code: ${n.qcode||'—'}<br>${n.text||''}</div>`}
function layerFor(n){if(!n.geometry)return null;const high=n.relevance==='HIGH_RELEVANCE',style={pane:'notamPane',weight:high?2:1.25,opacity:high?.8:.45,fillOpacity:high?.055:.018,color:high?'#dc2626':'#64748b'};const group=L.featureGroup();geometryParts(n.geometry).forEach(geometry=>{if(geometry.type==='Point'){const [lon,lat]=geometry.coordinates;L.circle([lat,lon],{...style,radius:Number(n.radius_km||0)*1000}).addTo(group)}else L.geoJSON(featureForGeometry(geometry),{pane:'notamPane',style}).addTo(group)});return group.getLayers().length?group:null}
function addCard(n,layer,target){const el=document.createElement('article');el.className=`card ${n.relevance==='HIGH_RELEVANCE'?'high':n.relevance.toLowerCase()}`;el.innerHTML=`<h3>${n.id} · ${n.category||n.relevance.replace('_RELEVANCE','')}</h3><div class="meta"><span class="relation">${relationToTask(n.distance_to_task_km)}</span> · ${n.lower_ft||0}–${n.upper_ft||'—'} ft</div><div class="meta">${displayTime(n.valid_from)} → ${displayTime(n.valid_to)} · Q ${n.qcode||'—'}</div><div>${n.text||''}</div>`;el.onclick=()=>{map.fitBounds(layer.getBounds().pad(.8));layer.openPopup()};target.appendChild(el)}
function filterNotams(){
  notamLayers.forEach(x=>map.removeLayer(x.layer));notamLayers=[];
  const found=(dataError?[]:notams.filter(relevant).map(n=>({...n,relevance:SoaringRelevance.classify(n),distance_to_task_km:distanceToTask(n)}))).sort(SoaringRelevance.compare);
  const groups={HIGH_RELEVANCE:[],RELEVANT:[],OTHER:[]};found.forEach(n=>groups[n.relevance].push(n));
  $('count').textContent=dataError?'Data unavailable':`${groups.HIGH_RELEVANCE.length} high · ${groups.RELEVANT.length} other relevant · ${found.length} total`;
  $('notamList').innerHTML='';$('notamActions').innerHTML='';
  if(!found.length){$('notamList').innerHTML=`<div class="empty">${dataError||'Create a task to show relevant NOTAMs.'}</div>`;return}
  if(groups.RELEVANT.length){const button=document.createElement('button');button.className='secondary';button.textContent=showRelevant||showAll?'Hide other relevant':`Show ${groups.RELEVANT.length} other relevant NOTAMs`;button.onclick=()=>{showRelevant=!showRelevant;if(!showRelevant)showAll=false;filterNotams()};$('notamActions').appendChild(button)}
  if(groups.OTHER.length){const button=document.createElement('button');button.className='secondary';button.textContent=showAll?'Hide low-value items':`Show all (${found.length})`;button.onclick=()=>{showAll=!showAll;if(showAll)showRelevant=true;filterNotams()};$('notamActions').appendChild(button)}
  const visible=[...groups.HIGH_RELEVANCE,...((showRelevant||showAll)?groups.RELEVANT:[]),...(showAll?groups.OTHER:[])];
  visible.forEach(n=>{const layer=layerFor(n);if(!layer)return;layer.addTo(map).bindPopup(popupHtml(n));notamLayers.push({id:n.id,layer})});
  [['HIGH_RELEVANCE','HIGH RELEVANCE'],['RELEVANT','OTHER RELEVANT'],['OTHER','ALL / OTHER']].forEach(([key,label])=>{if(!groups[key].length||(key==='RELEVANT'&&!showRelevant&&!showAll)||(key==='OTHER'&&!showAll))return;const title=document.createElement('h2');title.className='group-title';title.textContent=`${label} · ${groups[key].length}`;$('notamList').appendChild(title);groups[key].forEach(n=>{const entry=notamLayers.find(x=>x.id===n.id);if(entry)addCard(n,entry.layer,$('notamList'))})});
  if(track)track.bringToFront();
}
function restore(){try{const s=JSON.parse(localStorage.getItem(STORE));if(!s)return;['date','corridor','alt','taskType'].forEach(k=>{if(s[k])$(k).value=s[k]});(s.points||[]).forEach(([lat,lng])=>addPoint(L.latLng(lat,lng),false));rebuild();if(track)map.fitBounds(track.getBounds().pad(.25))}catch(e){console.warn('Saved task ignored',e)}}
function acceptData(payload){if(!payload||payload.source!=='FAA_NMS_STAGING'||!Array.isArray(payload.notams)||!payload.generated_at_utc)throw new Error('invalid schema');notams=payload.notams;const generated=new Date(payload.generated_at_utc),age=(Date.now()-generated.getTime())/60000;if(!Number.isFinite(age))throw new Error('invalid timestamp');const stamp=generated.toISOString().slice(11,16);$('sourceStatus').textContent=`FAA NMS STAGING · updated ${stamp} UTC${age>STALE_MINUTES?' · STALE':''}`;$('sourceStatus').classList.toggle('stale',age>STALE_MINUTES)}
fetch('data/notams-live.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}).then(x=>{acceptData(x);restore();filterNotams()}).catch(()=>{dataError='FAA NMS STAGING data is missing or invalid. No mock fallback is used.';$('sourceStatus').textContent='FAA NMS STAGING · DATA ERROR';$('sourceStatus').classList.add('error');restore();filterNotams()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
