const map=L.map('map').setView([52.15,5.35],8);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap contributors'}).addTo(map);
const $=id=>document.getElementById(id),STORE='soaring-notam-v12';$('date').value=new Date().toISOString().slice(0,10);
let points=[],markers=[],track=null,corridorLayer=null,notamLayers=[],notams=[];
const R=6371,rad=x=>x*Math.PI/180;
function hav(a,b){const dlat=rad(b.lat-a.lat),dlon=rad(b.lng-a.lng);const q=Math.sin(dlat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function segDistance(p,a,b){const lat0=rad(p.lat);const sx=x=>({x:rad(x.lng-p.lng)*Math.cos(lat0)*R,y:rad(x.lat-p.lat)*R});const A=sx(a),B=sx(b),vx=B.x-A.x,vy=B.y-A.y,wx=-A.x,wy=-A.y;const t=Math.max(0,Math.min(1,(wx*vx+wy*vy)/(vx*vx+vy*vy||1)));return Math.hypot(A.x+t*vx,A.y+t*vy)}
function legs(){if(points.length<2)return[];const arr=[];for(let i=0;i<points.length-1;i++)arr.push([points[i],points[i+1]]);if($('taskType').value==='triangle'&&points.length===3)arr.push([points[2],points[0]]);return arr}
function taskDistance(){return legs().reduce((s,[a,b])=>s+hav(a,b),0)}
function taskCoords(){if(points.length<2)return null;const c=points.map(p=>[p.lng,p.lat]);if($('taskType').value==='triangle'&&points.length===3)c.push([points[0].lng,points[0].lat]);return c}
function updateLegInfo(){const ls=legs();$('legInfo').innerHTML=ls.map(([a,b],i)=>`<span>Leg ${i+1}: <strong>${hav(a,b).toFixed(1)} km</strong></span>`).join('')}
function saveState(){localStorage.setItem(STORE,JSON.stringify({points:points.map(p=>[p.lat,p.lng]),date:$('date').value,corridor:$('corridor').value,alt:$('alt').value,taskType:$('taskType').value}))}
function rebuild(){if(track)map.removeLayer(track);if(corridorLayer)map.removeLayer(corridorLayer);track=null;corridorLayer=null;const ls=legs(),coords=taskCoords();if(ls.length){track=L.polyline(ls.map(x=>x.map(p=>[p.lat,p.lng])),{weight:4,opacity:.95}).addTo(map);if(coords&&window.turf){const buffered=turf.buffer(turf.lineString(coords),+$('corridor').value,{units:'kilometers',steps:32});corridorLayer=L.geoJSON(buffered,{style:{weight:1,opacity:.6,fillOpacity:.055}}).addTo(map)}}$('taskInfo').textContent=points.length?`${points.length} points · ${taskDistance().toFixed(0)} km task · ${$('corridor').value} km corridor`:'No task';updateLegInfo();filterNotams();saveState()}
function markerLabel(i){return i===0?'HOME':`TP${i}`}
function addPoint(latlng,doRebuild=true){if($('taskType').value==='triangle'&&points.length>=3)return;const i=points.length;points.push(latlng);const m=L.marker(latlng,{draggable:true}).addTo(map).bindTooltip(markerLabel(i),{permanent:true,direction:'top'});m.on('drag',()=>{points[i]=m.getLatLng();rebuild()});markers.push(m);if(doRebuild)rebuild()}
function clearTask(){points=[];markers.forEach(m=>map.removeLayer(m));markers=[];rebuild()}
map.on('click',e=>addPoint(e.latlng));$('start').onclick=clearTask;$('undo').onclick=()=>{if(!points.length)return;points.pop();map.removeLayer(markers.pop());rebuild()};$('demo').onclick=()=>{clearTask();[[52.191,5.146],[52.26,6.18],[52.78,6.49]].forEach(([lat,lng])=>addPoint(L.latLng(lat,lng),false));rebuild();if(track)map.fitBounds(track.getBounds().pad(.25))};
$('taskType').onchange=()=>{if($('taskType').value==='triangle'&&points.length>3){while(points.length>3){points.pop();map.removeLayer(markers.pop())}}rebuild()};['corridor','alt','date'].forEach(id=>$(id).onchange=rebuild);
function activeOn(n,date){return n.valid_from.slice(0,10)<=date&&n.valid_to.slice(0,10)>=date}
function relevant(n){if(points.length<2||n.status==='CANCELLED')return false;if(!activeOn(n,$('date').value))return false;if(n.lower_ft>+$('alt').value)return false;const p=L.latLng(n.lat,n.lon),d=Math.min(...legs().map(([a,b])=>segDistance(p,a,b)));return d<=+$('corridor').value+n.radius_km}
function popupHtml(n){return `<b>${n.id}</b> · ${n.category}<div class="popupmeta"><b>${n.status||'EXISTING'}</b><br>Q-code: ${n.qcode||'—'}<br>${n.lower_ft}–${n.upper_ft} ft<br>${n.valid_from.replace('T',' ')} → ${n.valid_to.replace('T',' ')}<br>${n.text}</div>`}
function filterNotams(){notamLayers.forEach(x=>map.removeLayer(x.layer));notamLayers=[];const found=notams.filter(relevant);$('count').textContent=`${found.length} relevant NOTAM${found.length===1?'':'s'}`;$('notamList').innerHTML=found.length?'':'<div class="empty">Create a task to show relevant test NOTAMs.</div>';found.forEach(n=>{const layer=L.circle([n.lat,n.lon],{radius:n.radius_km*1000,weight:2,fillOpacity:.13}).addTo(map).bindPopup(popupHtml(n));notamLayers.push({id:n.id,layer});const el=document.createElement('article');el.className='card';const st=(n.status||'EXISTING').toLowerCase();el.innerHTML=`<h3>${n.id} · ${n.category}<span class="badge ${st}">${n.status||'EXISTING'}</span></h3><div class="meta">Q ${n.qcode||'—'} · ${n.lower_ft}–${n.upper_ft} ft · radius ${n.radius_km} km</div><div class="meta">${n.valid_from.replace('T',' ')} → ${n.valid_to.replace('T',' ')}</div><div>${n.text}</div>`;el.onclick=()=>{map.fitBounds(layer.getBounds().pad(.8));layer.openPopup()};$('notamList').appendChild(el)})}
function restore(){try{const s=JSON.parse(localStorage.getItem(STORE));if(!s)return;['date','corridor','alt','taskType'].forEach(k=>{if(s[k])$(k).value=s[k]});(s.points||[]).forEach(([lat,lng])=>addPoint(L.latLng(lat,lng),false));rebuild();if(track)map.fitBounds(track.getBounds().pad(.25))}catch(e){console.warn('Saved task ignored',e)}}
fetch('data/mock-notams.json').then(r=>r.json()).then(x=>{notams=x;restore();filterNotams()}).catch(()=>{$('sourceStatus').textContent='TEST DATA ERROR';restore()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');