const map=L.map('map').setView([52.15,5.35],8);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap contributors'}).addTo(map);
for(const [name,z] of [['baselinePane',320],['notamPane',350],['corridorPane',420],['taskPane',460]]){map.createPane(name);map.getPane(name).style.zIndex=z}
const $=id=>document.getElementById(id),STORE='soaring-notam-v12',STALE_MINUTES=60,liveUrl=path=>`${path}?refresh=${Date.now()}`;$('date').value=new Date().toISOString().slice(0,10);
let points=[],markers=[],track=null,corridorLayer=null,notams=[],airspaces=[],dynamicRules=new Map(),dataError=null,baselineError=null,faaGenerated=null,faaPayload=null,openaipGenerated=null,faaRefreshStatus=null,showRelevant=false,showAll=false,soaringFilter=true,airspaceSelections={...BaselineAirspace.DEFAULTS},briefing=null,briefingCache={key:null,value:null},layerRegistry=new Map(),selectedTimer=null,restored=false,expandedGroups=new Set();
const activationSources={aupUup:ActivationSources.unavailable(ActivationSources.TYPES.AUP_UUP),aipSup:ActivationSources.unavailable(ActivationSources.TYPES.AIP_SUP)};
const taskWorkflow=TaskWorkflow.create();
const R=6371,rad=x=>x*Math.PI/180;
function hav(a,b){const dlat=rad(b.lat-a.lat),dlon=rad(b.lng-a.lng),q=Math.sin(dlat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function segDistance(p,a,b){const lat0=rad(p.lat),sx=x=>({x:rad(x.lng-p.lng)*Math.cos(lat0)*R,y:rad(x.lat-p.lat)*R}),A=sx(a),B=sx(b),vx=B.x-A.x,vy=B.y-A.y,wx=-A.x,wy=-A.y,t=Math.max(0,Math.min(1,(wx*vx+wy*vy)/(vx*vx+vy*vy||1)));return Math.hypot(A.x+t*vx,A.y+t*vy)}
function legs(){if(points.length<2)return[];const out=[];for(let i=0;i<points.length-1;i++)out.push([points[i],points[i+1]]);if($('taskType').value==='triangle'&&points.length===3)out.push([points[2],points[0]]);return out}
function taskDistance(){return legs().reduce((sum,[a,b])=>sum+hav(a,b),0)}
function taskCoords(){if(points.length<2)return null;const out=points.map(p=>[p.lng,p.lat]);if($('taskType').value==='triangle'&&points.length===3)out.push([points[0].lng,points[0].lat]);return out}
function corridorGeoJSON(){const coords=taskCoords();return coords&&window.turf?turf.buffer(turf.lineString(coords),+$('corridor').value,{units:'kilometers',steps:32}):null}
function feature(geometry){return geometry?{type:'Feature',properties:{},geometry}:null}
function geometryParts(geometry){return geometry&&geometry.type==='GeometryCollection'?geometry.geometries.flatMap(geometryParts):geometry?[geometry]:[]}
function intersectsCorridor(item,buffered){return geometryParts(item.geometry).some(geometry=>{try{if(geometry.type==='Point'&&item.radius_km)return turf.booleanIntersects(buffered,turf.buffer(feature(geometry),Number(item.radius_km),{units:'kilometers'}));return turf.booleanIntersects(buffered,feature(geometry))}catch{return false}})}
function pairOverlap(airspace,notam){return geometryParts(notam.geometry).some(geometry=>{try{const candidate=geometry.type==='Point'&&notam.radius_km?turf.buffer(feature(geometry),Number(notam.radius_km),{units:'kilometers'}):feature(geometry);return turf.booleanIntersects(feature(airspace.geometry),candidate)}catch{return false}})}
function distanceToTask(n){const ls=legs();if(!ls.length)return Infinity;let best=Infinity,direct=false;for(const geometry of geometryParts(n.geometry)){try{if(turf.booleanIntersects(turf.lineString(taskCoords()),feature(geometry)))direct=true}catch{}const pairs=[];(function collect(value){if(Array.isArray(value)&&value.length>=2&&typeof value[0]==='number')pairs.push(value);else if(Array.isArray(value))value.forEach(collect)})(geometry.coordinates);for(const [lon,lat] of pairs)best=Math.min(best,...ls.map(([a,b])=>segDistance(L.latLng(lat,lon),a,b)))}return direct?0:Math.max(0,best-Number(n.radius_km||0))}
function cacheKey(){return JSON.stringify({points:points.map(p=>[+p.lat.toFixed(5),+p.lng.toFixed(5)]),date:$('date').value,start:$('startTime').value,end:$('endTime').value,corridor:$('corridor').value,alt:$('alt').value,selections:airspaceSelections,notams:notams.length,airspaces:airspaces.length,dynamicRules:dynamicRules.size})}
function buildBriefing(){const key=cacheKey();if(briefingCache.key===key)return briefingCache.value;const window=BriefingSchedule.windowFor($('date').value,$('startTime').value,$('endTime').value),buffered=points.length>=2?corridorGeoJSON():null,max=+$('alt').value;const spatialNotams=!buffered||dataError||!airspaceSelections.faa?[]:notams.filter(n=>SoaringRelevance.verticalOverlap(n,0,max)&&intersectsCorridor(n,buffered)).map(n=>({...n,distance_to_task_km:distanceToTask(n)}));const allSpatialAirspaces=!buffered||baselineError?[]:airspaces.filter(a=>BaselineAirspace.verticalOverlap(a,max)&&intersectsCorridor(a,buffered));const visibleAirspaces=allSpatialAirspaces.filter(a=>BaselineAirspace.selected(a,airspaceSelections));const criteria={date:$('date').value,start_local:window.start_local,end_local:window.end_local,from_utc:window.from_utc,to_utc:window.to_utc,timezone:window.timezone,corridor_km:+$('corridor').value,max_altitude_ft:max,task_type:$('taskType').value,task_distance_km:+taskDistance().toFixed(1),points:points.map(p=>[p.lat,p.lng]),airspace_selections:{...airspaceSelections},soaring_filter:soaringFilter};const sources={...activationSources,notamEvidence:ActivationSources.notamEvidence(faaPayload,faaRefreshStatus,new Date(),STALE_MINUTES,window)};const value=TaskBriefing.build({window,spatialNotams,allSpatialAirspaces,visibleAirspaces,geometryOverlap:pairOverlap,classify:SoaringRelevance.classify,criteria,dynamicRules,activationSources:sources});briefingCache={key,value};return value}
function saveState(){localStorage.setItem(STORE,JSON.stringify({points:points.map(p=>[p.lat,p.lng]),taskMode:taskWorkflow.state,date:$('date').value,startTime:$('startTime').value,endTime:$('endTime').value,corridor:$('corridor').value,alt:$('alt').value,taskType:$('taskType').value,airspaceSelections}))}
function setTaskMessage(value=''){$('taskMessage').textContent=value}
function invalidatePrintState(){localStorage.removeItem(BriefingPrintState.STORE)}
function syncTaskState(){const drawing=!taskWorkflow.isFinished();$('taskState').textContent=taskWorkflow.state;$('taskState').classList.toggle('drawing',drawing);$('finishTask').hidden=!drawing;$('editTask').hidden=drawing;$('undo').disabled=!drawing||!points.length;for(const marker of markers)drawing?marker.dragging.enable():marker.dragging.disable()}
function renderTaskGraphics(){if(track)map.removeLayer(track);track=null;const ls=legs();if(ls.length)track=L.polyline(ls.map(x=>x.map(p=>[p.lat,p.lng])),{pane:'taskPane',interactive:false,weight:5,opacity:1}).addTo(map);$('taskInfo').textContent=points.length?`${points.length} points · ${taskDistance().toFixed(0)} km task · ${$('corridor').value} km corridor`:'No task';$('legInfo').innerHTML=ls.map(([a,b],i)=>`<span>Leg ${i+1}: <strong>${hav(a,b).toFixed(1)} km</strong></span>`).join('');syncTaskState()}
function lightweightTaskUpdate(){invalidatePrintState();renderTaskGraphics();saveState()}
function rebuild(){invalidatePrintState();if(corridorLayer)map.removeLayer(corridorLayer);corridorLayer=null;renderTaskGraphics();const buffered=taskWorkflow.isFinished()?corridorGeoJSON():null;if(buffered)corridorLayer=L.geoJSON(buffered,{pane:'corridorPane',interactive:false,style:{weight:1,opacity:.45,fillOpacity:.035}}).addTo(map);briefingCache.key=null;renderBriefing();saveState()}
function markerLabel(i){return i===0?'HOME':`TP${i}`}
function addPoint(latlng,doUpdate=true){if(!taskWorkflow.canAddPoint()||$('taskType').value==='triangle'&&points.length>=3)return;const i=points.length;points.push(latlng);const marker=L.marker(latlng,{draggable:true}).addTo(map).bindTooltip(markerLabel(i),{permanent:true,direction:'top'});marker.on('drag',()=>{points[i]=marker.getLatLng();lightweightTaskUpdate()});marker.on('dragend',()=>{points[i]=marker.getLatLng();rebuild()});markers.push(marker);if(doUpdate)lightweightTaskUpdate()}
function clearTask(recalculate=true){points=[];markers.forEach(marker=>map.removeLayer(marker));markers=[];taskWorkflow.newTask();setTaskMessage();recalculate?rebuild():lightweightTaskUpdate()}
function minimumPoints(){return $('taskType').value==='triangle'?3:2}
map.on('click',event=>addPoint(event.latlng));$('start').onclick=()=>clearTask();$('finishTask').onclick=()=>{if(points.length<minimumPoints()){setTaskMessage(`Add at least ${minimumPoints()} task points before finishing.`);return}taskWorkflow.finish(points.length);setTaskMessage();syncTaskState();rebuild()};$('editTask').onclick=()=>{taskWorkflow.edit();setTaskMessage();syncTaskState();saveState()};$('undo').onclick=()=>{if(taskWorkflow.canUndo()&&points.length){points.pop();map.removeLayer(markers.pop());lightweightTaskUpdate()}};$('demo').onclick=()=>{clearTask(false);[[52.191,5.146],[52.26,6.18],[52.78,6.49]].forEach(([lat,lng])=>addPoint(L.latLng(lat,lng),false));taskWorkflow.finish(points.length);syncTaskState();rebuild();if(track)map.fitBounds(track.getBounds().pad(.25))};
$('taskType').onchange=()=>{if($('taskType').value==='triangle'&&points.length>3)while(points.length>3){points.pop();map.removeLayer(markers.pop())}taskWorkflow.isFinished()?rebuild():lightweightTaskUpdate()};['corridor','alt','date','startTime','endTime'].forEach(id=>$(id).onchange=()=>{if($('endTime').value<=$('startTime').value){$('startTime').value='10:00';$('endTime').value='18:00'}rebuild()});
function displayTime(value){return value?value.replace('T',' ').replace(/:00Z$/,'Z'):'—'}function relation(distance){return distance<.05?'on route':`${distance<10?distance.toFixed(1):Math.round(distance)} km from task`}
function notamPopup(item){const n=item.notam,names=item.matches.filter(m=>AirspaceMatching.ROBUST.has(m.confidence)).map(m=>m.airspace.name);return`<b>${n.id}</b> · ${item.relevance.replace('_RELEVANCE','')}<div class="popupmeta"><b>${relation(n.distance_to_task_km)}</b><br>${n.lower_ft||0}–${n.upper_ft||'—'} ft<br>${displayTime(n.valid_from)} → ${displayTime(n.valid_to)}<br>Q-code: ${n.qcode||'—'}${names.length?`<br>Matched: ${names.join(', ')}`:''}<br>${n.text||''}</div>`}
function airspacePopup(item){const a=item.airspace,d=item.dynamic;return`<b>${a.name||a.id}</b> · ${a.type}<div class="popupmeta"><b>${d?d.status:item.status}</b><br>${a.country||'—'} · ${BaselineAirspace.limitText(a.lower_limit)}–${BaselineAirspace.limitText(a.upper_limit)}<br>${d?`${d.reason}<br>Provenance: ${d.source_type}${d.source_identifier?` · ${d.source_identifier}`:''}`:(a.by_notam?'Activation: by NOTAM':'Current activation not inferred')}<br>Baseline: OpenAIP</div>`}
function baselineStyle(item){const colors={prd:'#9f1239',flexible:'#7e22ce',ctr:'#2563eb',tma:'#0284c7',atz:'#0f766e',rmztmz:'#a16207'},status=item.status,dynamic=item.dynamic?.status;if(dynamic){const active=dynamic==='ACTIVE',partial=dynamic==='PARTLY_ACTIVE',unknown=dynamic==='UNKNOWN';return{pane:'baselinePane',color:active?'#dc2626':partial?'#ea580c':unknown?'#d97706':'#64748b',weight:active?3.5:partial?3:unknown?2:1,opacity:(active||partial) ? 0.95 : unknown ? 0.75 : 0.35,fillOpacity:active ? 0.16 : partial ? 0.11 : unknown ? 0.035 : 0.01,dashArray:unknown?'4 4':dynamic==='INACTIVE'?'2 6':null}}const risk=['PERMANENT PROHIBITED','ACTIVE BY NOTAM'].includes(status),scheduled=status==='SCHEDULED ACTIVE',uncertain=status.includes('uncertain')||status==='POSSIBLE MATCH';return{pane:'baselinePane',color:risk?'#dc2626':scheduled?'#ea580c':uncertain?'#d97706':colors[BaselineAirspace.groupFor(item.airspace)]||'#64748b',weight:risk?3:scheduled?2.5:uncertain?2:1.25,opacity:risk?.95:.55,fillOpacity:risk?.12:scheduled?.08:.02,dashArray:status.includes('NO ACTIVATION')||status.includes('unknown')?'5 5':uncertain?'3 4':null}}
function visibleNotamItems(model){const revealAll=showAll||!soaringFilter;return[...model.groups.HIGH_NOTAMS,...((showRelevant||revealAll)?model.groups.OTHER_RELEVANT_NOTAMS:[]),...(revealAll?model.groups.OTHER_NOTAMS:[])]}
function mappedNotamItems(model){const revealAll=showAll||!soaringFilter;return[...model.groups.HIGH_NOTAMS,...model.groups.OTHER_RELEVANT_NOTAMS,...(revealAll?model.groups.OTHER_NOTAMS:[])]}
function registerLayer(id,layer,style){layerRegistry.set(id,{layer,style});layer.on('click',()=>selectBriefing(id,false));layer.addTo(map)}
function renderMap(model){for(const {layer} of layerRegistry.values())map.removeLayer(layer);layerRegistry.clear();for(const item of model.all.airspaces){const style=baselineStyle(item),layer=L.geoJSON(feature(item.airspace.geometry),{pane:'baselinePane',style}).bindPopup(airspacePopup(item));registerLayer(item.stable_id,layer,style)}for(const item of mappedNotamItems(model)){const n=item.notam,groupKey=groupForItem(model,item.stable_id),visual=NotamMap.style({...n,relevance:item.relevance,status:item.status},groupKey),style={pane:'notamPane',color:visual.color,weight:visual.weight,opacity:visual.opacity,fillOpacity:visual.fillOpacity,dashArray:visual.dashArray},group=L.featureGroup();for(const descriptor of NotamMap.renderables(n))NotamMap.leafletLayer(L,descriptor,style,feature).addTo(group);if(group.getLayers().length){group.bindPopup(notamPopup(item));registerLayer(item.stable_id,group,style)}}if(track)track.bringToFront()}
function cardHtml(item){if(item.kind==='notam'){const n=item.notam,matched=item.matches.filter(m=>AirspaceMatching.ROBUST.has(m.confidence)).map(m=>m.airspace.name);return`<h3>${item.relevance.replace('_RELEVANCE','')} · ${n.id}</h3><div class="meta">${relation(n.distance_to_task_km)} · ${n.lower_ft||0}–${n.upper_ft||'—'} ft · ${n.status||'EXISTING'}</div><div class="meta">${displayTime(n.valid_from)} → ${displayTime(n.valid_to)} · Q ${n.qcode||'—'}</div>${matched.length?`<div class="match">Matched: ${matched.join(', ')}</div>`:''}<div>${n.text||''}</div>`}const a=item.airspace,d=item.dynamic;return`<h3>${d?d.status:item.status} · ${a.name||a.id}</h3><div class="meta">${a.type} · ${a.country||'—'} · ${BaselineAirspace.limitText(a.lower_limit)}–${BaselineAirspace.limitText(a.upper_limit)}</div><div class="meta">${d?`${d.reason} · ${d.source_type}${d.source_identifier?` · ${d.source_identifier}`:''}`:(a.by_notam?'Activation: by NOTAM · Source: OpenAIP':'Source: OpenAIP')}</div>${item.matches.length?`<div class="match">FAA: ${item.matches.map(m=>`${m.notam.id} (${m.confidence})`).join(', ')}</div>`:''}`}
function section(key,label,items){const node=document.createElement('section'),collapsible=BriefingUI.collapsedByDefault(key),collapsed=collapsible&&!expandedGroups.has(key);node.className='briefing-group';node.dataset.group=key;const heading=document.createElement('h2');if(collapsible){const toggle=document.createElement('button');toggle.type='button';toggle.className='section-toggle';toggle.setAttribute('aria-expanded',String(!collapsed));toggle.setAttribute('aria-controls',`group-${key}`);toggle.innerHTML=`<span class="arrow" aria-hidden="true">${collapsed?'▸':'▾'}</span>${label} (${items.length})`;toggle.onclick=()=>{collapsed?expandedGroups.add(key):expandedGroups.delete(key);renderPanel(briefing)};heading.appendChild(toggle)}else heading.textContent=`${label} (${items.length})`;node.appendChild(heading);const content=document.createElement('div');content.id=`group-${key}`;content.hidden=collapsed;for(const item of items){const card=document.createElement('article');card.className=`briefing-card ${item.kind}`;card.id=`brief-${item.stable_id}`;card.dataset.briefingId=item.stable_id;card.innerHTML=cardHtml(item);card.onclick=()=>selectBriefing(item.stable_id,true);content.appendChild(card)}node.appendChild(content);return node}
function groupForItem(model,id){return model.group_order.find(key=>model.groups[key].some(item=>item.stable_id===id))}
function renderPanel(model){const target=$('briefingList');target.innerHTML='';for(const key of model.group_order){if(key==='OTHER_NOTAMS'&&!(showAll||!soaringFilter))continue;target.append(section(key,model.group_labels[key],model.groups[key]))}$('attentionSummary').textContent=BriefingUI.summary(model);showRelevant=expandedGroups.has('OTHER_RELEVANT_NOTAMS');$('showRelevant').textContent=showRelevant?'Collapse operational NOTAMs':`Show operational NOTAMs (${model.groups.OTHER_RELEVANT_NOTAMS.length})`;$('showAll').textContent=showAll?'Hide all/diagnostic':`Show all (${model.all.notams.length})`}
function renderBriefing(){briefing=buildBriefing();renderMap(briefing);renderPanel(briefing);$('baselineCount').textContent=baselineError?'OpenAIP unavailable':`${briefing.all.airspaces.length} baseline airspaces`;$('count').textContent=dataError?'FAA unavailable':`${briefing.groups.HIGH_NOTAMS.length} primary · ${briefing.groups.OTHER_RELEVANT_NOTAMS.length} review · ${briefing.all.notams.length} total`}
function selectBriefing(id,fromPanel){document.querySelectorAll('.briefing-card.selected').forEach(el=>el.classList.remove('selected'));let card=document.getElementById(`brief-${id}`);if(briefing){const key=groupForItem(briefing,id),hidden=card&&card.parentElement.hidden;if(key&&BriefingUI.collapsedByDefault(key)&&(!card||hidden)){expandedGroups.add(key);renderPanel(briefing);card=document.getElementById(`brief-${id}`)}}if(card){card.classList.add('selected');if(!fromPanel)card.scrollIntoView({behavior:'smooth',block:'nearest'})}const entry=layerRegistry.get(id);if(!entry)return;const bounds=entry.layer.getBounds&&entry.layer.getBounds();if(fromPanel&&bounds&&bounds.isValid())map.fitBounds(bounds.pad(.5),{padding:[24,24],maxZoom:11});entry.layer.openPopup();if(entry.layer.setStyle){entry.layer.setStyle({weight:4,opacity:1});clearTimeout(selectedTimer);selectedTimer=setTimeout(()=>entry.layer.setStyle(entry.style),1600)}}
function renderAirspaceControls(){document.querySelectorAll('#airspaceControls input').forEach(input=>{input.checked=!!airspaceSelections[input.dataset.group];input.onchange=()=>{airspaceSelections[input.dataset.group]=input.checked;briefingCache.key=null;renderBriefing();saveState()}})}
function restore(){if(restored)return;restored=true;try{const state=JSON.parse(localStorage.getItem(STORE));if(state){['date','startTime','endTime','corridor','alt','taskType'].forEach(key=>{if(state[key])$(key).value=state[key]});if(state.airspaceSelections)airspaceSelections={...BaselineAirspace.DEFAULTS,...state.airspaceSelections};(state.points||[]).forEach(([lat,lng])=>addPoint(L.latLng(lat,lng),false));taskWorkflow.restore(state.taskMode,points.length>=minimumPoints()?points.length:0)}}catch(error){console.warn('Saved task ignored',error)}renderAirspaceControls();syncTaskState();taskWorkflow.isFinished()?rebuild():lightweightTaskUpdate();if(track)map.fitBounds(track.getBounds().pad(.25))}
$('soaringFilter').onclick=()=>{soaringFilter=!soaringFilter;showRelevant=showAll=false;expandedGroups.clear();$('soaringFilter').textContent=`Soaring filter: ${soaringFilter?'ON':'OFF'}`;briefingCache.key=null;renderBriefing()};$('showRelevant').onclick=()=>{expandedGroups.has('OTHER_RELEVANT_NOTAMS')?expandedGroups.delete('OTHER_RELEVANT_NOTAMS'):expandedGroups.add('OTHER_RELEVANT_NOTAMS');renderPanel(briefing)};$('showAll').onclick=()=>{showAll=!showAll;if(showAll){expandedGroups.add('OTHER_RELEVANT_NOTAMS');expandedGroups.add('OTHER_NOTAMS')}else expandedGroups.delete('OTHER_NOTAMS');renderMap(briefing);renderPanel(briefing)};$('printBriefing').onclick=()=>{if(!taskWorkflow.isFinished()||points.length<minimumPoints()){setTaskMessage('Finish the current task before printing the briefing.');return}try{briefingCache.key=null;briefing=buildBriefing();const state=TaskBriefing.printState(briefing,{faa:$('sourceStatus').textContent,openaip:$('baselineStatus').textContent});BriefingPrintState.write(localStorage,state);if(!BriefingPrintState.read(localStorage))throw new Error('print state verification failed');setTaskMessage();window.open('briefing.html','_blank','noopener')}catch(error){console.error('Print briefing unavailable',error);setTaskMessage('The current briefing could not be prepared for printing.')}};
function exportSources(){return{faa:$('sourceStatus').textContent,openaip:$('baselineStatus').textContent}}
function exportPreview(){const result=OpenAirExport.build(briefing,$('exportMode').value,exportSources());$('exportSummary').innerHTML=`<strong>${result.count} airspace objects will be exported</strong><br>${result.skipped} skipped due to unsupported/no geometry${result.warnings.length?`<br><span class="export-warning">${result.warnings.length} geometry/altitude warning(s) will be included</span>`:''}`;$('downloadOpenAir').disabled=!result.count;return result}
$('exportOpenAir').onclick=()=>{if(!briefing)return;$('exportMode').value=OpenAirExport.MODES.OPERATIONAL;exportPreview();$('exportDialog').showModal()};$('exportMode').onchange=exportPreview;$('downloadOpenAir').onclick=()=>{const result=exportPreview();if(!result.count)return;const url=URL.createObjectURL(new Blob([result.text],{type:'text/plain;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=result.filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('exportDialog').close()};
$('help').onclick=()=>{$('helpSources').textContent=`${$('sourceStatus').textContent}. ${$('baselineStatus').textContent}.`; $('helpDialog').showModal()};$('closeHelp').onclick=()=>$('helpDialog').close();
function renderFaaStatus(){if(!faaGenerated)return;const age=(Date.now()-faaGenerated.getTime())/60000,failed=faaRefreshStatus&&faaRefreshStatus.success===false,attempt=failed?new Date(faaRefreshStatus.last_attempt_utc):null,attemptText=attempt&&Number.isFinite(attempt.getTime())?` · REFRESH FAILED ${attempt.toISOString().slice(11,16)} UTC`:failed?' · REFRESH FAILED':'';$('sourceStatus').textContent=`FAA NMS STAGING · updated ${faaGenerated.toISOString().slice(11,16)} UTC${age>STALE_MINUTES?' · STALE':''}${attemptText}`;$('sourceStatus').classList.toggle('stale',age>STALE_MINUTES);$('sourceStatus').classList.toggle('error',failed)}
function acceptData(payload){if(!payload||payload.source!=='FAA_NMS_STAGING'||!Array.isArray(payload.notams)||!payload.generated_at_utc)throw new Error('invalid schema');faaPayload=payload;notams=payload.notams;faaGenerated=new Date(payload.generated_at_utc);if(!Number.isFinite(faaGenerated.getTime())||faaGenerated.getUTCFullYear()<2025)throw new Error('invalid timestamp');renderFaaStatus();briefingCache.key=null;restore();renderBriefing()}
fetch(liveUrl('data/notams-live.json'),{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(acceptData).catch(()=>{dataError='FAA NMS STAGING data is missing or invalid.';$('sourceStatus').textContent='FAA NMS STAGING · DATA ERROR';$('sourceStatus').classList.add('error');restore();renderBriefing()});
fetch(liveUrl('data/faa-refresh-status.json'),{cache:'no-store'}).then(r=>r.ok?r.json():null).then(status=>{if(status&&status.source==='FAA_NMS_STAGING_REFRESH'){faaRefreshStatus=status;renderFaaStatus();briefingCache.key=null;renderBriefing()}}).catch(()=>{});
function acceptBaseline(payload){if(!payload||payload.source!=='OPENAIP'||!Array.isArray(payload.airspaces)||payload.airspace_count!==payload.airspaces.length)throw new Error();airspaces=payload.airspaces;openaipGenerated=new Date(payload.generated_at_utc);$('baselineStatus').textContent=`OpenAIP baseline · updated ${openaipGenerated.toISOString().slice(11,16)} UTC`;briefingCache.key=null;renderBriefing()}
fetch(liveUrl('data/airspace-baseline.json'),{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(acceptBaseline).catch(()=>{baselineError='OpenAIP baseline unavailable';$('baselineStatus').textContent=baselineError;$('baselineStatus').classList.add('error');renderBriefing()});
fetch(liveUrl('data/dutch-dynamic-airspace.json'),{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(payload=>{dynamicRules=new Map((payload.airspaces||[]).map(rule=>[String(rule.id),rule]));briefingCache.key=null;renderBriefing()}).catch(error=>console.warn('Dutch dynamic-airspace matrix unavailable; status remains conservative',error));
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=2.8.1');
