(function(root,factory){const api=factory(root.AirspaceMatching||(typeof require==='function'?require('./matching.js'):null),root.BriefingSchedule||(typeof require==='function'?require('./schedule.js'):null),root.OperationalStatus||(typeof require==='function'?require('./operational-status.js'):null),root.DynamicAirspace||(typeof require==='function'?require('./dynamic-airspace.js'):null));if(typeof module==='object'&&module.exports)module.exports=api;else root.TaskBriefing=api})(typeof self!=='undefined'?self:this,function(M,S,O,D){
  const GROUP_ORDER=['DYNAMIC_ACTIVE','DYNAMIC_PARTLY_ACTIVE','DYNAMIC_UNKNOWN','DYNAMIC_INACTIVE','HIGH_NOTAMS','NOTAM_UNCERTAIN','POSSIBLE_MATCH','OTHER_RELEVANT_NOTAMS','OTHER_NOTAMS'];
  const LEGACY_GROUPS=['PERMANENT_PROHIBITED','ACTIVE_BY_NOTAM','SCHEDULED_ACTIVE','BY_NOTAM_NO_ACTIVATION','FLEXIBLE_BASELINE','CONTROLLED_BASELINE'];
  const LABELS={DYNAMIC_ACTIVE:'DYNAMIC AIRSPACE — ACTIVE',DYNAMIC_PARTLY_ACTIVE:'DYNAMIC AIRSPACE — PARTLY ACTIVE',DYNAMIC_UNKNOWN:'DYNAMIC AIRSPACE — UNRESOLVED / CHECK REQUIRED',DYNAMIC_INACTIVE:'DYNAMIC AIRSPACE — INACTIVE',PERMANENT_PROHIBITED:'PERMANENT PROHIBITED',ACTIVE_BY_NOTAM:'ACTIVE BY NOTAM',SCHEDULED_ACTIVE:'SCHEDULED ACTIVE',HIGH_NOTAMS:'HIGH / TEMPORARY FAA NOTAMs',NOTAM_UNCERTAIN:'NOTAM MATCH / activation uncertain',POSSIBLE_MATCH:'POSSIBLE MATCH',BY_NOTAM_NO_ACTIVATION:'BY NOTAM — NO ACTIVATION FOUND',FLEXIBLE_BASELINE:'FLEXIBLE BASELINE / status unknown',CONTROLLED_BASELINE:'CONTROLLED BASELINE / status unknown',OTHER_RELEVANT_NOTAMS:'OTHER OPERATIONAL NOTAMs',OTHER_NOTAMS:'OTHER NOTAMs — SHOW ALL'};
  function stableId(kind,id,index=0){return`${kind}:${String(id||index).replace(/[^A-Za-z0-9_.:-]/g,'_')}`}
  function reference(n){return String(n.notam_reference||n.id||'').toUpperCase().replace(/\s/g,'')}
  function lifecycle(notams,window){
    const all=notams||[],candidates=all.map(n=>({...n,schedule_evaluation:S.notamOverlap(n,window)})).filter(n=>n.schedule_evaluation.overlap),targets=new Set();
    for(const n of all)for(const value of [n.replaces_id,n.cancels_reference])if(value)targets.add(String(value).toUpperCase().replace(/\s/g,''));
    return candidates.filter(n=>{const type=String(n.notam_type||'').toUpperCase(),status=String(n.status||'').toUpperCase(),condition=String(n.qcode||'').toUpperCase().replace(/^Q/,'').slice(2,4),ended=type==='NOTAMC'||status==='CANCELLED'||status==='SUPERSEDED'||condition==='CN';return(!ended||M.deactivationSemantics(n))&&!n.replaced_by_id&&!targets.has(reference(n))});
  }
  function push(map,key,value){if(!map.has(key))map.set(key,[]);map.get(key).push(value)}
  function build(options){
    const operational=lifecycle(options.spatialNotams||[],options.window),matchByAirspace=new Map(),matchByNotam=new Map(),matchQuality={EXACT:0,STRONG:0,POSSIBLE:0,REJECTED:0};
    for(const airspace of options.allSpatialAirspaces||[])for(const notam of operational){const result=M.match(airspace,notam,options.geometryOverlap(airspace,notam));matchQuality[result.confidence]=(matchQuality[result.confidence]||0)+1;if(result.confidence==='REJECTED')continue;const association={...result,airspace,notam,schedule:notam.schedule_evaluation};push(matchByAirspace,airspace.id,association);push(matchByNotam,notam.id,association)}
    const notamItems=operational.map((notam,index)=>{const relevance=options.classify(notam);return{kind:'notam',stable_id:stableId('faa',notam.id,index),notam,relevance,classification:notam.relevance_classification||null,matches:matchByNotam.get(notam.id)||[]}});
    const airspaceItems=(options.visibleAirspaces||[]).map((airspace,index)=>{const matches=matchByAirspace.get(airspace.id)||[],status=O.statusFor(airspace,matches,options.window),rule=options.dynamicRules?.get(String(airspace.id))||{},dynamic=D.evaluate(airspace,matches,options.window,rule,options.activationSources||{});return{kind:'airspace',stable_id:stableId('airspace',airspace.id,index),airspace,matches,status,dynamic}});
    const keys=[...new Set([...GROUP_ORDER,...LEGACY_GROUPS])],groups=Object.fromEntries(keys.map(key=>[key,[]]));
    for(const item of airspaceItems){groups[O.groupFor(item)].push(item);if(item.dynamic)groups[`DYNAMIC_${item.dynamic.status}`].push(item)}for(const item of notamItems)groups[O.groupFor(item)].push(item);
    for(const key of keys)groups[key].sort((a,b)=>(O.RANK[a.status]??9)-(O.RANK[b.status]??9)||String(a.airspace?.name||a.notam?.id).localeCompare(String(b.airspace?.name||b.notam?.id)));
    return{version:3,generated_at_utc:new Date().toISOString(),criteria:options.criteria,group_order:GROUP_ORDER,group_labels:LABELS,groups,all:{notams:notamItems,airspaces:airspaceItems},counts:Object.fromEntries(keys.map(key=>[key,groups[key].length])),match_quality_counts:matchQuality};
  }
  function printItem(item){if(item.kind==='notam')return{kind:'notam',stable_id:item.stable_id,id:item.notam.id,relevance:item.relevance,classification:item.classification,text:item.notam.text,lower_ft:item.notam.lower_ft,upper_ft:item.notam.upper_ft,valid_from:item.notam.valid_from,valid_to:item.notam.valid_to,qcode:item.notam.qcode,status:item.notam.status,schedule_evaluation:item.notam.schedule_evaluation,distance_to_task_km:item.notam.distance_to_task_km,matched_airspaces:item.matches.filter(m=>M.ROBUST.has(m.confidence)).map(m=>m.airspace.name)};return{kind:'airspace',stable_id:item.stable_id,id:item.airspace.id,name:item.airspace.name,type:item.airspace.type,country:item.airspace.country,lower_limit:item.airspace.lower_limit,upper_limit:item.airspace.upper_limit,by_notam:item.airspace.by_notam,status:item.status,dynamic:item.dynamic,activation_note:item.airspace.activation_note,matched_notams:item.matches.map(m=>`${m.notam.id} (${m.confidence})`)}}
  function printState(model,sources){const group_order=model.group_order.filter(key=>key!=='OTHER_NOTAMS');return{version:model.version,generated_at_utc:model.generated_at_utc,criteria:model.criteria,sources,group_order,group_labels:model.group_labels,groups:Object.fromEntries(group_order.map(key=>[key,model.groups[key].map(printItem)])),match_quality_counts:model.match_quality_counts}}
  return{GROUP_ORDER,LEGACY_GROUPS,LABELS,build,lifecycle,printItem,printState,stableId};
});
