(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.BriefingCoverage=api})(typeof self!=='undefined'?self:this,function(){
  const COMPLETE='COMPLETE',PARTIAL='PARTIAL',UNKNOWN='UNKNOWN',TARGET_OPENAIP_COUNTRIES=['NL','BE','LU','DE','FR'];
  const FIR_OPENAIP_COUNTRIES={EHAA:['NL'],EBBU:['BE','LU'],EDGG:['DE'],EDWW:['DE'],EDMM:['DE'],LFFF:['FR'],LFEE:['FR'],LFBB:['FR'],LFMM:['FR'],LFRR:['FR']};
  function validate(payload){if(!payload||payload.schema_version!==1||!Array.isArray(payload.firs)||payload.firs.length!==10||!payload.combined_geometry)throw new Error('invalid briefing coverage');const ids=new Set(payload.firs.map(f=>f.identifier)),countries=new Set(payload.openaip_countries||[]);for(const id of payload.geographic_firs||[])if(!ids.has(id))throw new Error(`missing FIR ${id}`);if(countries.size!==TARGET_OPENAIP_COUNTRIES.length||TARGET_OPENAIP_COUNTRIES.some(country=>!countries.has(country)))throw new Error('invalid OpenAIP coverage target');return payload}
  function onSegment(p,a,b){const cross=(p[1]-a[1])*(b[0]-a[0])-(p[0]-a[0])*(b[1]-a[1]);return Math.abs(cross)<1e-9&&p[0]>=Math.min(a[0],b[0])-1e-9&&p[0]<=Math.max(a[0],b[0])+1e-9&&p[1]>=Math.min(a[1],b[1])-1e-9&&p[1]<=Math.max(a[1],b[1])+1e-9}
  function ringContains(point,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[j],b=ring[i];if(onSegment(point,a,b))return true;const crosses=(a[1]>point[1])!==(b[1]>point[1])&&point[0]<(b[0]-a[0])*(point[1]-a[1])/(b[1]-a[1])+a[0];if(crosses)inside=!inside}return inside}
  function polygonContains(point,rings){return Boolean(rings?.length&&ringContains(point,rings[0])&&!rings.slice(1).some(r=>ringContains(point,r)))}
  function geometryContains(geometry,point){if(!geometry||!Array.isArray(point)||point.length<2)return false;if(geometry.type==='Polygon')return polygonContains(point,geometry.coordinates);if(geometry.type==='MultiPolygon')return geometry.coordinates.some(p=>polygonContains(point,p));return false}
  function firForPoint(payload,point){validate(payload);return payload.firs.find(f=>geometryContains(f.geometry,point))?.identifier||null}
  function pointAllowed(payload,point){try{return Boolean(firForPoint(payload,point))}catch{return false}}
  function polygons(geometry){if(geometry?.type==='Polygon')return[geometry];if(geometry?.type==='MultiPolygon')return geometry.coordinates.map(coordinates=>({type:'Polygon',coordinates}));return[]}
  function subtract(corridor,firs,turf){if(!corridor||!turf?.difference||!turf?.featureCollection)throw new Error('coverage geometry unavailable');let remaining=corridor;for(const fir of firs)for(const geometry of polygons(fir.geometry)){if(!remaining)break;remaining=turf.difference(turf.featureCollection([remaining,{type:'Feature',properties:{},geometry}]))}return remaining}
  function component(corridor,firs,turf){try{const remaining=subtract(corridor,firs,turf);return!remaining||turf?.area&&turf.area(remaining)<1?COMPLETE:PARTIAL}catch{return UNKNOWN}}
  function relevantFirs(payload,corridor,turf){if(!corridor||!turf?.booleanIntersects)throw new Error('coverage intersection unavailable');return payload.firs.filter(f=>polygons(f.geometry).some(geometry=>turf.booleanIntersects(corridor,{type:'Feature',properties:{},geometry}))).map(f=>f.identifier)}
  function openaipComponent(payload,corridor,turf,availableCountries,geography){if(geography===UNKNOWN)return UNKNOWN;if(geography===PARTIAL)return PARTIAL;if(!Array.isArray(availableCountries))return UNKNOWN;const actual=new Set(availableCountries.filter(country=>TARGET_OPENAIP_COUNTRIES.includes(country))),required=new Set(relevantFirs(payload,corridor,turf).flatMap(fir=>FIR_OPENAIP_COUNTRIES[fir]||[]));return[...required].every(country=>actual.has(country))?COMPLETE:PARTIAL}
  function availableOpenAipCountries(payload){if(!payload||payload.source!=='OPENAIP'||!Array.isArray(payload.countries)||!Array.isArray(payload.airspaces))return null;const represented=new Set(payload.airspaces.map(item=>item?.country));return payload.countries.filter(country=>TARGET_OPENAIP_COUNTRIES.includes(country)&&represented.has(country))}
  function evaluate(payload,corridor,turf,openaipCountries){try{validate(payload);const geography=component(corridor,payload.firs,turf),faa=component(corridor,payload.firs.filter(f=>payload.faa_notam_firs.includes(f.identifier)),turf),openaip=openaipComponent(payload,corridor,turf,openaipCountries,geography),dynamicRules=geography,overall=[geography,openaip,faa,dynamicRules].includes(UNKNOWN)?UNKNOWN:[geography,openaip,faa,dynamicRules].includes(PARTIAL)?PARTIAL:COMPLETE;return{geography,openaip,faaNotam:faa,dynamicRules,overall,supportedFirs:[...payload.geographic_firs],faaFirs:[...payload.faa_notam_firs]}}catch{return{geography:UNKNOWN,openaip:UNKNOWN,faaNotam:UNKNOWN,dynamicRules:UNKNOWN,overall:UNKNOWN,supportedFirs:[],faaFirs:[]}}}
  function pilotText(value){if(!value||value.overall===UNKNOWN)return'COVERAGE · UNKNOWN — one or more coverage sources could not be evaluated';if(value.overall===PARTIAL){if(value.geography===PARTIAL)return'COVERAGE · PARTIAL — task corridor extends outside supported briefing area. Operational briefing is incomplete outside the supported coverage area.';if(value.openaip===PARTIAL)return'OPENAIP COVERAGE · PARTIAL — baseline country coverage is incomplete for this task';if(value.faaNotam===PARTIAL)return'FAA NOTAM COVERAGE · PARTIAL — France FAA NOTAM retrieval not yet enabled in this release';return'COVERAGE · PARTIAL — operational source coverage is incomplete'}return'COVERAGE · COMPLETE'}
  function dragDecision(payload,origin,candidate){return pointAllowed(payload,candidate)?{accepted:true,point:candidate,message:''}:{accepted:false,point:origin,message:'Outside briefing coverage. Task point restored.'}}
  function savedTaskDecision(payload,points){if(!payload)return{status:'PENDING'};try{validate(payload);const valid=Array.isArray(points)&&points.every(point=>Array.isArray(point)&&point.length===2&&point.every(Number.isFinite)&&pointAllowed(payload,[point[1],point[0]]));return{status:valid?'ACCEPT':'REJECT'}}catch{return{status:'PENDING'}}}
  return{COMPLETE,PARTIAL,UNKNOWN,TARGET_OPENAIP_COUNTRIES,validate,geometryContains,firForPoint,pointAllowed,dragDecision,savedTaskDecision,availableOpenAipCountries,evaluate,pilotText};
});
