(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.NotamMap=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const RED=new Set(['PERMANENT_PROHIBITED','ACTIVE_BY_NOTAM']),ORANGE=new Set(['NOTAM_UNCERTAIN','POSSIBLE_MATCH']);
  function parts(geometry){if(!geometry||typeof geometry!=='object')return[];if(geometry.type==='GeometryCollection')return(geometry.geometries||[]).flatMap(parts);return[geometry]}
  function renderables(notam){const output=[];for(const geometry of parts(notam&&notam.geometry)){if(geometry.type==='Point'&&Array.isArray(geometry.coordinates)){const radius=Number(notam.radius_km);output.push({kind:radius>0?'circle':'marker',coordinates:geometry.coordinates,radius_m:radius>0?radius*1000:null})}else if((geometry.type==='Polygon'||geometry.type==='MultiPolygon')&&Array.isArray(geometry.coordinates))output.push({kind:'area',geometry})}return output}
  function leafletLayer(L,descriptor,style,feature){if(descriptor.kind==='circle')return L.circle([descriptor.coordinates[1],descriptor.coordinates[0]],{...style,radius:descriptor.radius_m});if(descriptor.kind==='marker')return L.circleMarker([descriptor.coordinates[1],descriptor.coordinates[0]],{...style,radius:7,fillOpacity:.45});return L.geoJSON(feature(descriptor.geometry),{pane:'notamPane',style})}
  function significance(item,groupKey){const status=String(item&&item.operational_status||item&&item.status||'').toUpperCase();if(RED.has(groupKey)||status==='ACTIVE'||status==='ACTIVE BY NOTAM'||status==='PERMANENT PROHIBITED'||status==='SCHEDULED ACTIVE')return'critical';if(ORANGE.has(groupKey)||status.includes('UNCERTAIN')||status==='POSSIBLE MATCH')return'uncertain';return groupKey==='HIGH_NOTAMS'||item&&item.relevance==='HIGH_RELEVANCE'?'temporary':'context'}
  function style(item,groupKey){const level=significance(item,groupKey),palette={critical:'#dc2626',uncertain:'#ea580c',temporary:'#eab308',context:'#64748b'},color=palette[level];return{level,color,weight:level==='critical'?3:level==='uncertain'?2.5:2,opacity:level==='context'?.48:.9,fillOpacity:level==='critical'?.12:level==='uncertain'?.09:level==='temporary'?.07:.02,dashArray:level==='uncertain'?'4 4':null}}
  return{parts,renderables,leafletLayer,significance,style};
});
