(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.OpenAirExport=api})(typeof self!=='undefined'?self:this,function(){
  const MODES={OPERATIONAL:'operational',BY_NOTAM:'by-notam',ALL_VISIBLE:'all-visible'},ROBUST=new Set(['EXACT','STRONG']);
  const OPERATIONAL_GROUPS=new Set(['DYNAMIC_ACTIVE','DYNAMIC_PARTLY_ACTIVE','PERMANENT_PROHIBITED','ACTIVE_BY_NOTAM','SCHEDULED_ACTIVE','NOTAM_UNCERTAIN']);
  const FAA_Q_TYPES={RA:{ac:'R',ay:'TRA'},RD:{ac:'Q',ay:'D'},RP:{ac:'P',ay:'P'},RR:{ac:'R',ay:'R'},RT:{ac:'R',ay:'TFR'}};
  const FAA_RESTRICTED_TEXT=/\b(?:TFR|temporary flight restriction|temporary restricted (?:area|airspace)|restricted airspace|airspace (?:is )?closed|no flights? (?:are )?(?:allowed|permitted)|flight prohibited|prohibited airspace|temporary reserved area|temporary segregated area)\b/i;
  function clean(value,max=90){return String(value||'').replace(/[\r\n*]+/g,' ').replace(/\s+/g,' ').trim().slice(0,max)}
  function airType(a){return String(a&&a.type||'').toUpperCase()}
  function qSubject(notam){const code=String(notam&&notam.qcode||'').toUpperCase().replace(/^Q/,'');return /^[A-Z]{2}/.test(code)?code.slice(0,2):''}
  function faaAreaType(notam){const subject=qSubject(notam);if(FAA_Q_TYPES[subject])return FAA_Q_TYPES[subject];if(subject)return null;return FAA_RESTRICTED_TEXT.test(`${notam&&notam.category||''} ${notam&&notam.text||''}`)?{ac:'R',ay:'TFR'}:null}
  function isExportableFaaArea(notam){return Boolean(faaAreaType(notam))}
  function classAndType(a,faa=false){const type=airType(a);if(faa)return faaAreaType(a);if(type.includes('PROHIBITED'))return{ac:'P',ay:'P'};if(type.includes('RESTRICTED'))return{ac:'R',ay:'R'};if(type.includes('DANGER'))return{ac:'Q',ay:'Q'};if(type==='TRA'||type==='TSA')return{ac:'R',ay:type};const ay=type.includes('MCTR')?'MATZ':type.includes('CTR')?'CTR':type.includes('MTMA')?'TMA':type.includes('TMA')?'TMA':type.includes('ATZ')?'ATZ':type.includes('RMZ')?'RMZ':type.includes('TMZ')?'TMZ':'CUSTOM';return{ac:'UNC',ay}}
  function limit(value,upper=false){if(!value)return upper?'UNL':'GND';const n=Number(value.value),unit=String(value.unit||'').toUpperCase(),ref=String(value.reference||'').toUpperCase();if(!Number.isFinite(n))return upper?'UNL':'GND';if(ref==='GND'&&n===0)return'GND';if(unit==='FL')return`FL${String(Math.round(n)).padStart(3,'0')}`;const suffix=ref==='AGL'?'AGL':ref==='GND'?'AGL':ref==='STD'?'STD':'MSL';return`${Number.isInteger(n)?n:+n.toFixed(1)} ${unit==='M'?'M':'FT'} ${suffix}`}
  function faaLimit(value,upper=false){const n=Number(value);if(!Number.isFinite(n))return upper?'UNL':'GND';if(!upper&&n===0)return'GND';return`${Math.round(n)} FT`}
  function dms(value,lat){const hemi=value<0?(lat?'S':'W'):(lat?'N':'E'),absolute=Math.abs(Number(value)),degrees=Math.floor(absolute),minutesFloat=(absolute-degrees)*60,minutes=Math.floor(minutesFloat),seconds=(minutesFloat-minutes)*60;return`${String(degrees).padStart(lat?2:3,'0')}:${String(minutes).padStart(2,'0')}:${seconds.toFixed(2).padStart(5,'0')} ${hemi}`}
  function point(coord){return`${dms(coord[1],true)} ${dms(coord[0],false)}`}
  function geometryParts(geometry){if(!geometry||typeof geometry!=='object')return[];if(geometry.type==='Polygon')return[{kind:'polygon',coordinates:geometry.coordinates}];if(geometry.type==='MultiPolygon')return geometry.coordinates.map(coordinates=>({kind:'polygon',coordinates}));if(geometry.type==='Point')return[{kind:'point',coordinates:geometry.coordinates}];if(geometry.type==='GeometryCollection')return(geometry.geometries||[]).flatMap(geometryParts);return[]}
  function isFlexible(item){const type=airType(item&&item.airspace);return['PROHIBITED','RESTRICTED','DANGER','TRA','TSA'].some(value=>type.includes(value))}
  function selectedAirspaces(model,mode){if(mode===MODES.ALL_VISIBLE)return model.all.airspaces.slice();const keys=new Set(OPERATIONAL_GROUPS);if(mode===MODES.BY_NOTAM){keys.add('BY_NOTAM_NO_ACTIVATION');keys.add('FLEXIBLE_BASELINE');keys.add('DYNAMIC_UNKNOWN')}const selected=[...keys].flatMap(key=>model.groups[key]||[]).filter(item=>item.kind==='airspace');if(mode===MODES.BY_NOTAM)selected.push(...(model.groups.POSSIBLE_MATCH||[]).filter(item=>item.kind==='airspace'&&isFlexible(item)));return selected}
  function candidates(model,mode){const airspaces=selectedAirspaces(model,mode),ids=new Set(airspaces.map(item=>String(item.airspace.id))),notams=model.groups.HIGH_NOTAMS.filter(item=>item.notam&&item.notam.geometry&&isExportableFaaArea(item.notam)&&!item.matches.some(match=>ROBUST.has(match.confidence)&&ids.has(String(match.airspace.id))));return[...airspaces,...notams]}
  function record(item,part,index,total,criteria,warnings){const faa=item.kind==='notam',value=faa?item.notam:item.airspace,source=faa?'FAA NMS':value.baseline_source==='NL_AIP_SUP'?'NL AIP SUP':'OpenAIP',status=faa?'HIGH TEMPORARY FAA':item.status,mapping=classAndType(value,faa);if(!mapping)return null;const{ac,ay}=mapping,baseName=clean(faa?(value.location&&value.location!=='EHAA'?`${value.location} ${value.id}`:value.id):value.name||value.id),name=clean(`${baseName} ${status}`),suffix=total>1?`-${index+1}`:'';
    const lines=[`* SOURCE: ${source}`,`* STATUS: ${clean(status)}`,`* BRIEFING: ${criteria.date} ${criteria.start_local}-${criteria.end_local} ${criteria.timezone}`,faa?`* NOTAM: ${clean(value.notam_reference||value.id)}`:`* AIRSPACE ID: ${clean(value.id)}`];
    if(faa)lines.push('* ALTITUDE WARNING: FAA numeric limits retained; source vertical datum is unavailable in the briefing model');if(status.includes('uncertain'))lines.push('* WARNING: activation uncertain');
    lines.push(`AC ${ac}`,`AY ${ay}`,`AN ${name}${suffix}`,`AL ${faa?faaLimit(value.lower_ft):limit(value.lower_limit)}`,`AH ${faa?faaLimit(value.upper_ft,true):limit(value.upper_limit,true)}`);
    if(part.kind==='point'){if(!faa||!Number.isFinite(Number(value.radius_km))||Number(value.radius_km)<=0)return null;lines.push(`V X=${point(part.coordinates)}`,`DC ${(Number(value.radius_km)/1.852).toFixed(2)}`)}else{const ring=part.coordinates&&part.coordinates[0];if(!Array.isArray(ring)||ring.length<3)return null;if(part.coordinates.length>1){warnings.push(`${baseName}: polygon holes are not representable in OpenAir and were omitted`)}for(const coordinate of ring)if(Array.isArray(coordinate)&&coordinate.length>=2&&coordinate.every(Number.isFinite))lines.push(`DP ${point(coordinate)}`);if(lines.filter(line=>line.startsWith('DP ')).length<3)return null}
    return lines.join('\n')}
  function build(model,mode=MODES.OPERATIONAL,sources={}){if(!Object.values(MODES).includes(mode))throw new Error('Unknown export mode');const warnings=[],blocks=[],seen=new Set(),items=candidates(model,mode),criteria=model.criteria||{},skipped=[];for(const item of items){const key=item.stable_id;if(seen.has(key))continue;seen.add(key);const value=item.kind==='notam'?item.notam:item.airspace,parts=geometryParts(value.geometry);if(!parts.length){skipped.push(key);continue}let emitted=0;parts.forEach((part,index)=>{const output=record(item,part,index,parts.length,criteria,warnings);if(output){blocks.push(output);emitted++}});if(!emitted)skipped.push(key)}const header=['*VERSION: 2.1','*WRITTEN_BY: Soaring NOTAM V2.5',`* TASK: ${clean(criteria.task_type)} ${criteria.task_distance_km||0} km; corridor ${criteria.corridor_km||0} km; max ${criteria.max_altitude_ft||0} FT`,`* WINDOW: ${criteria.date||''} ${criteria.start_local||''}-${criteria.end_local||''} ${criteria.timezone||''}`,`* SOURCES: FAA ${clean(sources.faa)}; OpenAIP ${clean(sources.openaip)}`,`* EXPORT MODE: ${mode}; AREAS: ${blocks.length}; SKIPPED: ${skipped.length}`,`* UNCERTAIN INCLUDED: ${mode===MODES.OPERATIONAL||mode===MODES.BY_NOTAM?'YES':'AS VISIBLE'}`];warnings.forEach(warning=>header.push(`* WARNING: ${clean(warning,160)}`));const text=blocks.length?`${header.join('\n')}\n\n${blocks.join('\n\n')}\n`:'';return{text,count:blocks.length,skipped:skipped.length,warnings,filename:`soaring-notam-${clean(criteria.date||'task').replace(/[^0-9A-Za-z-]/g,'-')}-task-openair.txt`}}
  function validate(text){const errors=[],blocks=String(text||'').split(/\n\s*\n/).filter(block=>/^AC /m.test(block));blocks.forEach((block,index)=>{for(const tag of ['AC ','AN ','AL ','AH '])if(!block.split('\n').some(line=>line.startsWith(tag)))errors.push(`block ${index+1}: missing ${tag.trim()}`);const dp=(block.match(/^DP /gm)||[]).length,circle=/^V X=/m.test(block)&&/^DC \d/m.test(block);if(dp<3&&!circle)errors.push(`block ${index+1}: unusable geometry`)});if(!blocks.length)errors.push('no airspace blocks');return{valid:errors.length===0,errors,areas:blocks.length}}
  return{MODES,build,classAndType,dms,geometryParts,isExportableFaaArea,limit,validate};
});
